responses:
  422:
    description: |
        Проверка данных завершилась неудачно.
        Подробные сообщения об ошибках смотрите в теле ответа.
    body:
        application/json:
            # type: !include /traits/schema/errors.json
            example: !include ../example/errors.json