queryParameters:
  fields:
    type: string
    required: false
    description: Ограничение списка полей в теле ответа
    example: id,title
  expand:
    type: string
    required: false
    description: Включить в ответ дополнительные поля или связанные данные
    example: profile,balance
